from vpython import vector

CONTAINER_LENGTH = 100
CONTAINER_HEIGHT = 50
CONTAINER_WIDTH = 50
TEXTURE_DEPTH = 1

CONTAINER_OFFSET = vector(CONTAINER_LENGTH*1.1, CONTAINER_HEIGHT*1.01, CONTAINER_WIDTH*1.2)
